### PR TITLE
improving seo, deadlinks

### LINKED ISSUE #95: Improve SEO on developers.kodadot.xyz
Good head start, I guess! Funny, it has indexed most webpages out of all (hello and kodadot)

I've used https://www.checkbot.io/
image

### LINKED ISSUE #100: Improve SEO of developers.kodadot.xyz
- [x] **Submit your site to Google**: Do this via Google's Search Console. This informs Google your site exists and requests it to crawl your site.
- [ ] **Check your `robots.txt` file and `meta` tags**: Ensure they're not inadvertently blocking Google from indexing your site or any of its important pages.
- [ ] **Improve your SEO**: This might include using relevant keywords in your content, optimizing your meta descriptions and alt tags, using semantic HTML, etc.
- [ ] **Generate backlinks**: Try to get other credible sites to link to yours, this increases your site's visibility and makes it easier for Google to find.
- [ ] **Improve your website's speed and mobile optimization**: Use tools and strategies to achieve this, from optimizing images to minimizing CSS and JavaScript.

### PR DESCRIPTION
**Pull request by poppyseedDev**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Contributes to  #100 
- [x] Contributes to #95 
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [ ] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

## Copilot Summary
image
This link didn't work

copilot:summary

copilot:poem

### CODE REVIEW

**Comment by yangwao** [comment]
> Check your robots.txt file and meta tags: Ensure they're not inadvertently blocking Google from indexing your site or any of its important pages.

I don't see robotss.txt here nor meta tags 
- https://github.com/kodadot/docs/blob/main/developers/.vitepress/config.ts

> Polkadot NFT marketplace

I don't see any mention of it? 
> Improve your SEO: This might include using relevant keywords in your content, optimizing your meta descriptions and alt tags, using semantic HTML, etc.

**Comment by yangwao** [comment]
Still poor when I've checked with checkbot.io https://deploy-preview-104--developers-kodadot.netlify.app/

image

**Comment by yangwao** [comment]
Inspire yourself 
- https://github.com/kodadot/subwork/blob/main/docs/.vitepress/config.ts#L49

**Comment by poppyseedDev** [comment]
@yangwao

**Pull request merged**
