### PR TITLE
cleaned up FAQ

### PR DESCRIPTION
**Pull request by thea-exe**

### CODE REVIEW

**Comment by cryptodamsky** [comment]
Hey, so i'm wondering, will you be working more on those FAQ? I realize that some of the questions are duplicate, but usually those docs FAQ are same as FAQ on kodadot.xyz landing page and they answer most of the questions we collected throughout the time. 

Simply we don't to repeat ourselves and just point people to FAQ somewhere where are the questions answered. I feel like by deleting so many of them, we'll have to add them later anyway because we don't want to waste time by explaining everything one by one.

**Comment by thea-exe** [comment]
I will be adding more! It was overwhelming  to me at first so I decided to
take the most important and keep it there.

I was also thinking that maybe I can find some really begineer-friendly
resources that I can link to without having to take up a ton of space on
the FAQs

**Comment by cryptodamsky** [comment]
Uhm yeah, so can we actually agree on removing some duplicate or obsolent questions, but keeping most of them? We actually use it as a mekka where all information is and we don't want to link some other publications or repositories because we want to keep users at the docs, not send them somewhere. 

I'd be happier if most of the questions stayed because it also took us some time to collect them and also to create an answer to them. I actually send these FAQ from time to time as an answer to a user and i wouldn't wanna lose these.

**Review by cryptodamsky — COMMENTED** [review]
So i believe those reviewed ones -mainly the incentives can be reworked in some way, but we definitely need to keep the tutorials for now:D Let's please not delete those.

**Review by cryptodamsky — CHANGES_REQUESTED** [review]
Can we please bring back get_featured.md, technology.md and how-to-bug-report.md?

Please let's not that drastically delete tutorials and files we are sending to artists, let's first talk on the changes and then make them. 

We are thinking about this quite easy way - we have to document our incentives and we need to send some information to the artists (for example get-featured.md) and it's not effective to write it one by one therefore we have docs for it.

As same with tutorials - It's nice to have them in screenshot way and also in the video way, you can make the videos but please let's not delete the screenshot tuts. Let people choose which way they want to learn about something

**Comment by cryptodamsky** [comment]
For example the idea of technology.md is that we collect as much information as possible around cryptocurrencies and instead of users trying to find something on the internet, we have in the docs as kinda proofed materials for people to learn. I think it's better than sending some people away to look for themselves. What do you think?

**Comment by thea-exe** [comment]
Yeah of course! I’ll be adding back what I deleted, it’s just going to take
some time to reword :) so you don’t have to merge it just yet!

**Pull request merged**
